spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: sales

logging:
    level:
        org:
            springframework:
                web: ${LOG_LEVEL:DEBUG}
        com:
            montebruni:
                sales: ${LOG_LEVEL:DEBUG}
